### ISSUE TITLE
Python vs. nginx

### ISSUE THREAD

**Issue by EpicVoyage** [chr15m/piku-redirect#1]
Hi, I appreciate your contributions to the `piku` project, and came across this sample code. It does install and run the Python interpreter, and your update with piku/piku#79 gives us the ability to create a redirect via an `nginx.conf` extension.

Would you be open to a pull request moving to nginx directives?

Pros:
- Uses fewer resources.

Cons:
- Old domain would be in `ENV`
- New domain would be in `nginx.conf`

If you would prefer, I could simply make the nginx version a separate public repo.

**Comment by chr15m** [comment]
Yes for sure, most welcome, will merge.

**Comment by EpicVoyage** [comment]
Created pull request #2.
